# Generated by Django 6.0.2 on 2026-02-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barb_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao_minutos', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data', models.DateField(default=False)),
                ('hora', models.TimeField(default=False)),
                ('barb_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.barbeiro')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servico')),
            ],
            options={
                'unique_together': {('barb_nome', 'data', 'hora')},
            },
        ),
    ]
